config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'

  resources :users, :except => [:new]
  get '/signup' => 'users#new'

  resources :sessions, :except => [:new, :create, :destroy]
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  resources :posts do
    resources :responses, :only => [:new, :create, :update, :destroy]
    post :vote
  end

  resources :admin do
    put :toggle
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :responses
  validates :title, :presence => true
  validates :body, :presence => true
  scope :count_today, -> { where("created_at >= ?", Time.now.beginning_of_day).count}
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :votes
  scope :count_today, -> {where("created_at >= ?", Time.now.beginning_of_day).count}
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  validates :name, :presence => true, :uniqueness => true
  before_save :encrypt_password
  has_many :posts
  has_many :responses
  has_many :votes
  before_destroy :destroy_responses_and_posts

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(account, password)
    user = User.find_by "email = ? OR name = ?", account, account
    # user_name = User.find_by "name = ?",
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def destroy_responses_and_posts
    self.responses.destroy_all
    self.posts.destroy_all
  end

  def toggle_admin_status
    if self.permission == 'user'
      self.update(permission: 'admin')
    else
      self.update(permission: 'user')
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :response
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize_admin

  def index
    @posts = Post.all
    @users = User.all
    @responses = Response.all
    @number_of_posts_from_today = Post.count_today
    @number_of_responses_from_today = Response.count_today
  end

  def toggle
    @user = User.find(params[:format])
    @user.toggle_admin_status
    redirect_to '/admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/signin'
    end
  end

  def authorize_user_page
    if current_user.id != params['id'].to_i && current_user.permission != 'admin'
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/signin'
    end
  end

  def authorize_admin
    if current_user.permission != 'admin'
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: [:new]

  def index
    @posts = Post.all.page(params[:page])
  end

  def new
    @user = User.find(session[:user_id])
    @post = Post.new
  end

  def create
    @user = User.find(session[:user_id])
    @post = Post.new(post_params)
    if @post.save
      flash[:alert] = "Post successfully created."
      redirect_to post_path(@post)
    else
      flash[:alert] = "Post not created, please check your submission."
      redirect_to '/posts/new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def vote
    @post = Post.find(params[:post_id])
    @user = User.find(session[:user_id])
    @response = Response.find(params[:format])
    Vote.create(user_id: @user.id, response_id: @response.id, count: 1)
    redirect_to post_path(@post)
  end

private
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
  def vote_params
    params.require(:vote).permit(:user_id, :response_id, :count)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = Response.new
    @post = Post.find(params[:post_id])
    @user = User.find(session[:user_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @user = User.find(session[:user_id])
    @response = Response.new(response_params)
    if @response.save
      flash[:alert] = "Response successfully posted"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Response not created, please check your submission."
      redirect_to new_post_response_path(@post)
    end
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    redirect_to post_path(params[:post_id])
  end

private
  def response_params
    params.require(:response).permit(:comment, :user_id, :post_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]
  before_action :authorize_user_page, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/signup"
    else
      flash[:alert] = "There was a problem signing up"
      redirect_to '/signup'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      flash[:alert] = "🤬🤬🤬🤬🤬 #{@user.name}, please stop trying to delete yourself!! 🤬🤬🤬🤬🤬"
      redirect_to '/admin'
    else
      @user.destroy
      redirect_to '/admin'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :permission)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Admin Space</h1>

<p>Questions asked today: <%= @number_of_posts_from_today %></p>

<p>Responses posted today: <%= @number_of_responses_from_today %></p>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel heading</div>
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Permission</th>
      <th>Delete User</th>
      <th>Toggle Admin Role</th>
    </tr>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.permission %></td>
        <td><%= link_to 'Delete User', user_path(user), :data => {:confirm => "You sure you want to delete #{user.name}?", :method => 'delete'} %></td>
        <td><%= link_to 'Toggle', admin_toggle_path(session[:user_id], user), :data => {:method => 'put'}%></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflowClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-brand"><%= link_to "Home", posts_path %></p>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "New Post", new_post_path %></li>
        <li><%= link_to "Admin", admin_index_path %></li>
        <li><a href="#">Link</a></li>
      </ul>
      <p class="navbar-text navbar-right"><% if current_user %>
        <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
      <% else %>
        <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
      <% end %></p>
    </div>
  </div>
  </nav>
  <body>
    <div class="container">


      <div class="flash">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Question" %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>
  
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/posts/index.html.erb
<%= page_entries_info @posts %>

<% @posts.each do |post| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title"><%= link_to post.title, post_path(post) %></p>
      <p class="text-right"><%= post.user.name %></p>
    </div>
    <div class="panel-body question-preview">
      <p><%= post.body %></p>
    </div>
  </div>
<% end %>

<nav class="navbar navbar-default navbar-fixed-bottom pagination">
  <%= paginate @posts %>
</nav>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @post.title %></h1>
  </div>
  <div class="panel-body">
    <p><%= @post.body %></p>
  </div>
</div>
  <% if current_user %>
    <% @post.responses.each do |response| %>
    <div class="panel panel-default">
        <div class="panel-body">
          <p> Number of Votes: <%= response.votes.count %></p>
          <p><%= response.comment %></p>
          <p><%= response.user.name %></p>
          <% if response.user_id == session[:user_id] %>
            <p><%= link_to 'Delete Response', post_response_path(@post, response), :data => {:method => 'delete', :id => response.id} %></p>
          <% end %>
          <span><%= link_to "Vote Up", post_vote_path(@post, response), :data => {:method => 'post'}, class: 'btn btn-primary' %></span>
        </div>
    </div>
    <% end %>
<span><%= link_to "Add Response", new_post_response_path(@post), class: 'btn btn-primary' %></span>
<% else %>
<p>Login to see answers to this post.</p>
  <% end %>

app/views/responses/_form.html.erb
<%= form_for [@post, @response] do |f| %>
  <div class="form-group">
    <%= f.label :comment, "Comment" %>
    <%= f.text_field :comment, class: 'form-control' %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :post_id, value: @post.id %>

  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/responses/new.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label "Email" %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "User Name" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Password" %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit "Sign Up", class: 'btn btn-success'%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>